plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

group = 'com.shekarmudaliyar.social_share'
version = '1.0-SNAPSHOT'

android {
    namespace = 'com.shekarmudaliyar.social_share'
    compileSdk = 34

    defaultConfig {
        minSdk = 16
        testInstrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }

    lint {
        disable += 'InvalidPackage'
    }
}

dependencies {
    implementation 'com.facebook.android:facebook-share:17.0.2'
}
